# Generated by Django 5.2 on 2025-04-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_phone_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'permissions': [('can_publish_phone', 'Can publish phone')]},
        ),
    ]
