# Generated by Django 5.2 on 2025-04-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_phone_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='file',
            field=models.FileField(default='0', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='phone',
            table='upload_file',
        ),
    ]
