# Generated by Django 5.2 on 2025-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_phone_file_alter_phone_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='file',
            field=models.FileField(upload_to='file'),
        ),
    ]
